spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_todo
    username: nobopay
    password: n0b0p@y
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081
  servlet:
    context-path: /todoapp
